-- -----------------------------------------------------------------------
-- -----------------------------------------------------------------------
-- NPO PROJECT
-- AB,KFW,LR
drop table if exists db_npo;

create database db_npo;

use db_npo;

create table main (
EIN varchar(9),
NAME varchar(70),
ZIP varchar(10),
noemplyeesw3cnt int(1),
ORGCD varchar(6),
ntmaj5 varchar(2),
ntmaj10 varchar(2),
ntmaj12 varchar(2),
LEVEL1 varchar(14),
MAJGRPB varchar(2),
totreprtabled int(1),
totcomprelatede int(1),
totestcompf int(1),
noindiv100kcnt int(1),
nocontractor100kcnt int(1),
totcntrbgfts int(1),
prgmservcode2acd int(1),
totrev2acola int(1),
prgmservcode2bcd int(1),
totrev2bcola int(1),
prgmservcode2ccd int(1),
totrev2ccola int(1),
prgmservcode2dcd int(1),
totrev2dcola int(1),
prgmservcode2ecd int(1),
totrev2ecola int(1),
totrev2fcola int(1),
totprgmrevnue int(1),
invstmntinc int(1),
txexmptbndsproceeds int(1),
royaltsinc int(1),
grsrntsreal int(1),
grsrntsprsnl int(1),
rntlexpnsreal int(1),
rntlexpnsprsnl int(1),
rntlincreal int(1),
rntlincprsnl int(1),
netrntlinc  int(1),
grsalesecur int(1),
grsalesothr int(1),
cstbasisecur int(1),
cstbasisothr int(1),
gnlsecur int(1),
gnlsothr int(1),
netgnls int(1),
grsincfndrsng int(1),
lessdirfndrsng int(1),
netincfndrsng int(1),
grsincgaming int(1),
lessdirgaming int(1),
netincgaming int(1),
grsalesinvent int(1),
lesscstofgoods int(1),
netincsales int(1),
miscrev11acd int(1),
miscrevtota int(1),
miscrev11bcd int(1),
miscrevtot11b int(1),
miscrev11ccd int(1),
miscrevtot11c int(1),
miscrevtot11d int(1),
miscrevtot11e int(1),
totrevenue int(1),
grntstogovt int(1),
grnsttoindiv int(1),
grntstofrgngovt int(1),
benifitsmembrs int(1),
compnsatncurrofcr int(1),
compnsatnandothrothrsalwages int(1),
pensionplancontrb int(1),
othremplyeebenef int(1),
payrolltx int(1),
feesforsrvcmgmt int(1),
legalfees int(1),
accntingfees int(1),
feesforsrvclobby int(1),
profndraising int(1),
feesforsrvcinvstmgmt int(1),
feesforsrvcothr int(1),
advrtpromo int(1),
officexpns int(1),
infotech int(1),
royaltsexpns int(1),
occupancy int(1),
travel int(1),
travelofpublicoffcl int(1),
converconventmtng int(1),
interestamt int(1),
pymtoaffiliates int(1),
deprcatndepletn int(1),
insurance int(1),
othrexpnsa int(1),
othrexpnsb int(1),
othrexpnsc int(1),
othrexpnsd int(1),
othrexpnse int(1),
othrexpnsf int(1),
totfuncexpns int(1),
nonintcashend int(1),
svngstempinvend int(1),
pldgegrntrcvblend int(1),
accntsrcvblend int(1),
currfrmrcvblend int(1),
rcvbldisqualend int(1),
notesloansrcvblend int(1),
invntriesalesend int(1),
prepaidexpnsend int(1),
lndbldgsequipend int(1),
invstmntsend int(1),
invstmntsothrend int(1),
invstmntsprgmend int(1),
intangibleassetsend int(1),
othrassetsend int(1),
totassetsend int(1),
accntspayableend int(1),
grntspayableend int(1),
deferedrevnuend int(1),
txexmptbndcd int(1),
txexmptbndsend int(1),
escrwaccntliabend int(1),
paybletoffcrsend int(1),
secrdmrtgsend int(1),
unsecurednotesend int(1),
othrliabend int(1),
totliabend int(1),
unrstrctnetasstsend int(1),
temprstrctnetasstsend int(1),
permrstrctnetasstsend int(1),
capitalstktrstend int(1),
paidinsurplusend int(1),
retainedearnend int(1),
totnetassetend int(1),
totnetliabastend int(1),
primary key (EIN)
);

create table cities (
ZIP integer(5),
CITY varchar(22),
STATE varchar(2),
primary key (ZIP)
);

alter table main add constraint
foreign key (ZIP) references cities (ZIP) on delete no action on update no action;
